### ISSUE TITLE
[FEATURE] <ASTRA82001-I am logged in>

### ISSUE THREAD

**Issue by Jondalar-64** [EPFL-ENAC/resslab-astra_82001#1]
**Is your feature request related to a problem? Please describe.**
Hello, this is Alain and this is just a test. I saw I already have an account.
- How do you see me, I guess not as Alain Nussbaumer ?
- Shall I create another, say to differentiate private and epfl ?
- the Github is not for what I write/ask above, or is it ? if yes, where, in which category to put this ?
Best regards,
Alain

**Comment by guilbep** [comment]
Good Job @Jondalar-64 !

1) I guess it's okay, If I see you as Jondalar-64
2) It's okay to use your personnal github imho
3) It's for everything! But usually we use issues to discuss bugs/specs project related question. I set up a discussion here: https://github.com/EPFL-ENAC/resslab-astra_82001/discussions/2


Best regards!

**Comment by Jondalar-64** [comment]
Bonjour Pierre, l'invitation est pour la semaine prochaine, mais on se voit demain à 13h30, non ?

**Comment by guilbep** [comment]
Bonjour @Jondalar-64, oui demain par Zoom. L'invitation a la bonne date, j'ai du me tromper dans le calendrier!

Merci

**Comment by Jondalar-64** [comment]
cela a coupé, je ne peux plus me reconnecter
