### ISSUE TITLE
[DOC] Project documentation 

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/resslab-astra_82001#11]
- [x] GitHub readme

**Comment by guilbep** [comment]
done ine 5efe455 (HEAD -> dev, origin/dev) docs: add usage in readme closes #11

**Comment by guilbep** [comment]
@charlottegiseleweil  ça te va ? ce que j'ai fait https://github.com/EPFL-ENAC/resslab-astra_82001/commit/5efe455ca05df0c5efa03de387f5805d8f16d802#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5 ?
