### ISSUE TITLE
[DOC] Variables description (multi-language)

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/resslab-astra_82001#8]
- [x] @guilbep Prepare a file with symbols, names and descriptions (in all languages: FR, EN, IT, DE) -> [internationalization.csv](https://github.com/EPFL-ENAC/resslab-astra_82001/blob/main/src/assets/data/internationalization.csv) 
- [x] Edit the [internationalization.csv](https://github.com/EPFL-ENAC/resslab-astra_82001/blob/main/src/assets/data/internationalization.csv) file with relevant description in all languages. 

Reference from @Jondalar-64 : https://github.com/EPFL-ENAC/resslab-astra_82001/discussions/10

**Comment by guilbep** [comment]
@PaolaCostanzaMiglietta Hi! I updated the internationalization.csv file.
Internationalization is ready on my side

**Comment by PaolaCostanzaMiglietta** [comment]
Thank you @guilbep. Still awaiting approval by Dimitrios and @Jondalar-64 and validation for the German part.

**Comment by PaolaCostanzaMiglietta** [comment]
> I reviewed this file. I think I modified and saved it the proper way. Not all issues solved though. In particular for lines 29 to 33, these are incorrect as one shall use the definitions in french from § 5.3.3, pp. 47-48, of report 82001. I started modifying the english and french ones. Also, trans for me refers to transverse (or in the transverse direction), nothing to do with transmission. I modified but needs to be checked.

Somehow, my edits were overwritten by this change. I will incorporate them again in a new branch starting from this latest version created by Alain.

**Comment by guilbep** [comment]
@PaolaCostanzaMiglietta don't forget to push the branch to github. I cannot see your changes so far:
Here are the branches: https://github.com/EPFL-ENAC/resslab-astra_82001/branches

**Comment by guilbep** [comment]
@PaolaCostanzaMiglietta  je vois les branches maintenant! Je m'attendais à voir des pull requests:

Je peux voir maintenant les pulls requests ici: https://github.com/EPFL-ENAC/resslab-astra_82001/pull/29 et https://github.com/EPFL-ENAC/resslab-astra_82001/pull/28

Je vais m'occuper de mettre à jour. Merci!

**Comment by Dimitrios-astra** [comment]
Sorry one little mistake on the last one:
 Midspan transverse moment = Biegemoment in der Mitte der Spannweite in Querrichtung

**Comment by guilbep** [comment]
Thank you everyone:  @Dimitrios-astra  @PaolaCostanzaMiglietta I've updated the web app with the latest csv: https://github.com/EPFL-ENAC/resslab-astra_82001/blob/main/src/assets/data/internationalization.csv
